### PR TITLE
Support Django 2.2+, drop Python 2.7, support more Python versions

### PR DESCRIPTION
**Pull request by hrichards**
CC @lucaswiman 

Upgrade `django-predicate` to support more modern versions of Python and Django, drop old versions and shims.

# Background

Hi, @lucaswiman!  I hope you're well!  Yes, I'm still with Myriad.  We miss you!Mind taking a look at this PR and cutting a new version that supports Django 2.2+?  Thanks.

# What Changed

1. Converted from Nose to Pytest.
2. Removed Python version `if/else` blocks referencing old Python or Django versions.
3. Removed `six` and all references/uses to this library: since Python 2.7 has been removed (see below), `six` is by definition no longer required.
4. Reworked a lot of code around the removal of `iteritems` to be replaced with regular `items` iteration.
5. Reworked the `tox.ini` environments to support all valid combinations of Python and Django versions according to their respective release status pages.
6. Rewrote Tox targets `clean` and `report/stats` to equal the default recommended versions for Pytest, since we're now using `pytest-coverage` to calculate coverage.

# Outstanding Issues

- I see that there's a `.travis.yml` file in this repo: how do I get those tests to run?
- I had to stop at Django 4.1 because of errors in 4.2, which I believe might be due to the DeMorgan's Law work-arounds needed in prior versions.  I believe the rewrites in "negated expressions" might have changed enough of the `Q` internals to change (or maybe even fix!) how negation works in QuerySets: https://code.djangoproject.com/ticket/16211.  If you'd like to take a crack at fixing that in this PR, I'm willing to wait, but perhaps we should try supporting 4.2+ in another PR?

# How tested

The entire test suite passes for me locally (and I've confirmed Tox isn't doing that thing where it silently installs only the versions in `requirements.txt` instead of the versions requested in `tox.ini`).  I've written up the steps to run these tests in the README:

```
[...]
report create: /Users/hunter/git/django-predicate/.tox/report
report installdeps: coverage
report installed: coverage==7.4.1
report run-test-pre: PYTHONHASHSEED='1443967536'
report run-test: commands[0] | coverage report
Name                        Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------
predicate/__init__.py           4      0      0      0   100%
predicate/debug.py             59      7      2      0    89%
predicate/lookup_utils.py      97      0     38      1    99%
predicate/predicate.py        304     17    135      6    94%
-------------------------------------------------------------
TOTAL                         464     24    175      7    95%
report run-test: commands[1] | coverage html
Wrote HTML report to htmlcov/index.html
______________________________________________________________________________________________________________________ summary ______________________________________________________________________________________________________________________
  lint: commands succeeded
  clean: commands succeeded
  py36-1.11-postgres: commands succeeded
  py36-1.11-sqlite: commands succeeded
  py36-2.2-postgres: commands succeeded
  py36-2.2-sqlite: commands succeeded
  py36-3.2-postgres: commands succeeded
  py36-3.2-sqlite: commands succeeded
  py37-1.11-postgres: commands succeeded
  py37-1.11-sqlite: commands succeeded
  py37-2.2-postgres: commands succeeded
  py37-2.2-sqlite: commands succeeded
  py37-3.2-postgres: commands succeeded
  py37-3.2-sqlite: commands succeeded
  py310-3.2-postgres: commands succeeded
  py310-3.2-sqlite: commands succeeded
  py310-4.1-postgres: commands succeeded
  py310-4.1-sqlite: commands succeeded
  report: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Review by lucaswiman — COMMENTED** [review]
> I see that there's a .travis.yml file in this repo: how do I get those tests to run?

Travis no longer supports running free on open source projects, so I don't think they run anymore.

I think setting up github actions as a CI is standard now, but out of scope in this PR. Seems fine to run the tests manually.

Changes look good overall; I will review in more detail later. Could you bump the package version and create a "Changelog" section in the README?

**Comment by hrichards** [comment]
Okay, I bumped the package version and added a changelog.  I tried to get GHA test running to work, but failed, mostly on account of lack of Python 3.6 support in GHA.  Thanks for your time, @lucaswiman!

**Comment by lucaswiman** [comment]
Edited the README a bit and pushed to pypi: https://pypi.org/project/django-predicate/2.0.1/

Thanks @hrichards!

**Comment by anandsahuja** [comment]
Nice thanks @lucaswiman!

**Pull request merged**
